-- GENERATED by scripts/generate-sign-seed.mjs - do not edit by hand.
-- Placeholder sign library (344 signs: 45 glyphs x 1 style(s)
-- x 7 colorways from the asset manifest, plus 29 mock signs with no
-- art yet) and 20 of each for the six test agencies.
-- NOT auto-applied; run after 20261007_booking_inventory_holds.sql. Idempotent.

WITH glyph(prefix, sign_type, category, ch, w, h, file) AS (VALUES
  ('letter-a', 'letter', 'Letters', 'A', 27, 29, 'A.png'),
  ('letter-b', 'letter', 'Letters', 'B', 25, 30, 'B.png'),
  ('letter-c', 'letter', 'Letters', 'C', 22, 29, 'C.png'),
  ('letter-d', 'letter', 'Letters', 'D', 24, 29, 'D.png'),
  ('letter-e', 'letter', 'Letters', 'E', 21, 29, 'E.png'),
  ('letter-f', 'letter', 'Letters', 'F', 21, 29, 'F.png'),
  ('letter-g', 'letter', 'Letters', 'G', 26, 30, 'G.png'),
  ('letter-h', 'letter', 'Letters', 'H', 25, 29, 'H.png'),
  ('letter-i', 'letter', 'Letters', 'I', 14, 29, 'I.png'),
  ('letter-j', 'letter', 'Letters', 'J', 23, 30, 'J.png'),
  ('letter-k', 'letter', 'Letters', 'K', 26, 31, 'K.png'),
  ('letter-l', 'letter', 'Letters', 'L', 20, 29, 'L.png'),
  ('letter-m', 'letter', 'Letters', 'M', 31, 30, 'M.png'),
  ('letter-n', 'letter', 'Letters', 'N', 28, 29, 'N.png'),
  ('letter-o', 'letter', 'Letters', 'O', 27, 27, 'O.png'),
  ('letter-p', 'letter', 'Letters', 'P', 25, 30, 'P.png'),
  ('letter-q', 'letter', 'Letters', 'Q', 28, 32, 'Q.png'),
  ('letter-r', 'letter', 'Letters', 'R', 25, 29, 'R.png'),
  ('letter-s', 'letter', 'Letters', 'S', 23, 30, 'S.png'),
  ('letter-t', 'letter', 'Letters', 'T', 24, 29, 'T.png'),
  ('letter-u', 'letter', 'Letters', 'U', 26, 29, 'U.png'),
  ('letter-v', 'letter', 'Letters', 'V', 27, 29, 'V.png'),
  ('letter-w', 'letter', 'Letters', 'W', 36, 29, 'W.png'),
  ('letter-x', 'letter', 'Letters', 'X', 27, 29, 'X.png'),
  ('letter-y', 'letter', 'Letters', 'Y', 27, 29, 'Y.png'),
  ('letter-z', 'letter', 'Letters', 'Z', 21, 29, 'Z.png'),
  ('number-0', 'number', 'Numbers', '0', 26, 29, '0.png'),
  ('number-1', 'number', 'Numbers', '1', 19, 29, '1.png'),
  ('number-2', 'number', 'Numbers', '2', 22, 30, '2.png'),
  ('number-3', 'number', 'Numbers', '3', 23, 31, '3.png'),
  ('number-4', 'number', 'Numbers', '4', 23, 30, '4.png'),
  ('number-5', 'number', 'Numbers', '5', 23, 30, '5.png'),
  ('number-6', 'number', 'Numbers', '6', 24, 30, '6.png'),
  ('number-7', 'number', 'Numbers', '7', 22, 29, '7.png'),
  ('number-8', 'number', 'Numbers', '8', 24, 30, '8.png'),
  ('number-9', 'number', 'Numbers', '9', 24, 29, '9.png'),
  ('punct-exclamation', 'punctuation', 'Punctuation', '!', 14, 31, 'exclamation.png'),
  ('punct-question', 'punctuation', 'Punctuation', '?', 23, 31, 'question.png'),
  ('punct-ampersand', 'punctuation', 'Punctuation', '&', 27, 28, 'ampersand.png'),
  ('punct-apostrophe', 'punctuation', 'Punctuation', '''', 13, 16, 'apostrophe.png'),
  ('punct-period', 'punctuation', 'Punctuation', '.', 13, 12, 'period.png'),
  ('punct-comma', 'punctuation', 'Punctuation', ',', 13, 16, 'comma.png'),
  ('punct-hyphen', 'punctuation', 'Punctuation', '-', 17, 11, 'hyphen.png'),
  ('shape-heart', 'shape', 'Shapes', NULL, 26, 24, 'heart.png'),
  ('shape-star', 'shape', 'Shapes', NULL, 25, 24, 'star.png')
),
asset AS (
  SELECT g.prefix || '-' || st || '-' || c AS asset_key,
         COALESCE(g.ch, split_part(g.prefix, '-', 2)) || ' (' || st || '/' || c || ')' AS name,
         g.category, g.sign_type, g.ch, st AS style, c AS colorway, g.w, g.h,
         '/sign-assets/' || st || '/' || c || '/' || g.file AS img
  FROM glyph g
  CROSS JOIN unnest(ARRAY['classic']) AS st
  CROSS JOIN unnest(ARRAY['red', 'blue', 'pink', 'gold', 'green', 'purple', 'black']) AS c
),
mock(asset_key, name, category, sign_type, ch, w, h) AS (VALUES
  ('mock-ordinal-st', 'Ordinal ST', 'Ordinals', 'ordinal', 'ST', 18, 18),
  ('mock-ordinal-nd', 'Ordinal ND', 'Ordinals', 'ordinal', 'ND', 18, 18),
  ('mock-ordinal-rd', 'Ordinal RD', 'Ordinals', 'ordinal', 'RD', 18, 18),
  ('mock-ordinal-th', 'Ordinal TH', 'Ordinals', 'ordinal', 'TH', 18, 18),
  ('mock-decoration-baseball', 'Baseball', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-soccer-ball', 'Soccer Ball', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-basketball', 'Basketball', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-gaming-controller', 'Gaming Controller', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-music-notes', 'Music Notes', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-art-palette', 'Art Palette', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-crown', 'Crown', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-castle', 'Castle', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-superhero-shield', 'Superhero Shield', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-stars', 'Stars', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-rainbow', 'Rainbow', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-flowers', 'Flowers', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-heart', 'Heart', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-wand', 'Wand', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-shield', 'Shield', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-cape', 'Cape', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-mask', 'Mask', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-balloon', 'Balloon', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-gift', 'Gift', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-decoration-bow', 'Bow', 'Decorations', 'decoration', NULL, 24, 24),
  ('mock-backdrop-balloon-cluster', 'Balloon Cluster', 'Backdrops', 'backdrop', NULL, 12, 12),
  ('mock-backdrop-confetti', 'Confetti', 'Backdrops', 'backdrop', NULL, 12, 12),
  ('mock-backdrop-streamers', 'Streamers', 'Backdrops', 'backdrop', NULL, 12, 12),
  ('mock-bookend-left-bookend', 'Left Bookend', 'Bookends', 'bookend', NULL, 18, 48),
  ('mock-bookend-right-bookend', 'Right Bookend', 'Bookends', 'bookend', NULL, 18, 48)
),
all_signs AS (
  SELECT asset_key, name, category, sign_type, ch, style, colorway, w, h, img FROM asset
  UNION ALL
  SELECT asset_key, name, category, sign_type, ch, NULL, NULL, w, h,
         '/placeholder/' || asset_key || '.png' FROM mock
)
INSERT INTO sign_library (id, asset_key, name, category, sign_type, "character",
  style, colorway, size_width, size_height, image_url, is_platform, updated_at)
SELECT 'sign_' || asset_key, asset_key, name, category, sign_type, ch, style,
       colorway, w, h, img, true, now()::timestamp
FROM all_signs
ON CONFLICT (id) DO UPDATE SET
  asset_key = EXCLUDED.asset_key, name = EXCLUDED.name, category = EXCLUDED.category,
  sign_type = EXCLUDED.sign_type, "character" = EXCLUDED."character",
  style = EXCLUDED.style, colorway = EXCLUDED.colorway,
  size_width = EXCLUDED.size_width, size_height = EXCLUDED.size_height,
  image_url = EXCLUDED.image_url, updated_at = now()::timestamp;

INSERT INTO agency_inventory (id, agency_id, sign_id, quantity, available_quantity,
  allocated_quantity, deployed_quantity, updated_at)
SELECT 'inv_' || md5(a.id || ':' || s.id), a.id, s.id, 20, 20, 0, 0, now()::timestamp
FROM agencies a
CROSS JOIN sign_library s
WHERE a.slug IN ('elite-denver', 'lederman-bonds', 'my-business', 'sunny-signs-ca', 'texas-signs', 'yardcard-elite-west-branch')
  AND s.asset_key IS NOT NULL
ON CONFLICT (agency_id, sign_id) DO NOTHING;
